### ISSUE TITLE
Call volume not responding to changes

### ISSUE THREAD

**Issue by rojona** [xLexip/pe#11]
Changing the call volume during a call makes no difference for me, except when using BT headset. The volume seems to be stuck on the loudest in both top speaker and bottom speaker. Further more, the loudest volume of the top speaker is a tad too low, much lower than in other roms. 

PixelExperience_dumpling-11.0-20201222-0946-BETA-UNOFFICIAL

**Comment by xLexip** [comment]
Please try again with the new build
