### ISSUE TITLE
NFC not working?

### ISSUE THREAD

**Issue by El-Danoun** [xLexip/pe#13]
**Bug Description:**
I can't turn on NFC.

**How to reproduce:**
1. flash the rom
2. power on the device
3.  go to settings, try to turn on NFC
4. Nothing happens

**Expected behavior:**
I except my device to activate NFC

**Screenshots / Screen-casts:**

**Device:**
 - Model: [Dumpling (5T)
 - Build date: 11-PLUS: 2021-03-13
 - Rooted: no

**Comment by xLexip** [comment]
![Screenshot_20210314-091458_Settings](https://user-images.githubusercontent.com/46321162/111061935-22e80280-84a6-11eb-8997-e2dbe0eace19.png)

It works fine on my dumpling.
Please explain what you mean with "Nothing happens". Include screenshots/screencasts and check if nfc work anyways (even if it doesn't show that it's enabled).

**Comment by xLexip** [comment]
Closing the issue: No response. And it works for others (dumpling aswell as cheese).

**Comment by El-Danoun** [comment]
Sorry for the delay...


https://user-images.githubusercontent.com/29207399/111327809-fe3e8700-866d-11eb-8c6b-f488cf340492.mp4

**Comment by xLexip** [comment]
> Sorry for the delay...
> 
>  screen-20210316-141945_xLKs4X8n.mp4

Try clearing the data of the apps "Settings" and "NfcService".

**Comment by El-Danoun** [comment]
I tried, but it didn't work...

I think I'm going to wipe my device and install pixel experience again.

Thx for your help ! I hope it'll fix the issue.

Have a good day !

**Comment by xLexip** [comment]
> I tried, but it didn't work...
> 
> I think I'm going to wipe my device and install pixel experience again.
> 
> Thx for your help ! I hope it'll fix the issue.
> 
> Have a good day !

Yeah that should definitely work. Make sure you do not restore any system apps/parts from a backup.

**Comment by El-Danoun** [comment]
I did it twice, it still doesn't work :( 

I don't really know how to check if it's not an issue from the hardware...

calling *#808# doesn't work neither
