### ISSUE TITLE
Face recognition does not work

### ISSUE THREAD

**Issue by neisor** [xLexip/pe#18]
Hi,

The Face recognition does not work. I am on fresh installation of Pixel Experience 11, OnePlus 5T, latest build, no root, no Xposed, no custom kernel.

I have created my facial scan but it doesn't unlock my phone.

Any ideas why?

Thank you

**Comment by xLexip** [comment]
Heyo, it definitely does work for me and others. 
I'm really busy at the moment so please ask for support at **t.me/lexipg**.
Thanks.
