### ISSUE TITLE
VPN Connection issue

### ISSUE THREAD

**Issue by otohime-inari** [xLexip/pe#20]
PPTP
07-14 14:36:59.088 21312 21312 D mtpd    : Waiting for control socket
07-14 14:36:59.282 21312 21312 D mtpd    : Received 20 arguments
07-14 14:36:59.282 21312 21312 I mtpd    : Using protocol pptp
07-14 14:36:59.282 21312 21312 I mtpd    : Connecting to 11.11.11.111 port 1723 via rmnet_data0
07-14 14:36:59.427 21312 21312 I mtpd    : Connection established (socket = 8)
07-14 14:36:59.427 21312 21312 D mtpd    : Sending SCCRQ
07-14 14:36:59.508 21312 21312 D mtpd    : Received SCCRP -> Sending OCRQ (local = 12281)
07-14 14:36:59.508 21312 21312 I mtpd    : Tunnel established
07-14 14:36:59.571 21312 21312 D mtpd    : Received OCRQ (remote = 43)
07-14 14:36:59.571 21312 21312 I mtpd    : Session established
07-14 14:36:59.573 21312 21312 F mtpd    : Failed to create PPTP socket (Address family not supported by protocol)

L2TP
07-14 14:48:07.391 24295 24295 D mtpd    : Waiting for control socket
07-14 14:48:07.579 24295 24295 D mtpd    : Received 20 arguments
07-14 14:48:07.579 24295 24295 I mtpd    : Using protocol l2tp
07-14 14:48:07.579 24295 24295 I mtpd    : Connecting to 22.22.22.222 port 1701 via rmnet_data0
07-14 14:48:07.581 24295 24295 I mtpd    : Connection established (socket = 8)
07-14 14:48:07.581 24295 24295 D mtpd    : Sending SCCRQ (local_tunnel = 33756)
07-14 14:48:09.585 24295 24295 D mtpd    : Timeout -> Sending SCCRQ
07-14 14:48:09.644 24295 24295 D mtpd    : Received SCCRP (remote_tunnel = 43) -> Sending SCCCN
07-14 14:48:09.705 24295 24295 D mtpd    : Received ACK -> Sending ICRQ (local_session = 51108)
07-14 14:48:09.705 24295 24295 I mtpd    : Tunnel established
07-14 14:48:09.780 24295 24295 D mtpd    : Received ICRP (remote_session = 1) -> Sending ICCN
07-14 14:48:09.854 24295 24295 D mtpd    : Received ACK
07-14 14:48:09.855 24295 24295 I mtpd    : Session established
07-14 14:48:09.855 24295 24295 I mtpd    : Creating PPPoX tunnel socket...
07-14 14:48:09.855 24295 24295 F mtpd    : Tunnel socket(): Address family not supported by protocol

**Device:**
 - Model: Dumpling (5T)
 - Build date: 20210620-0510-UNOFFICIAL
 - Rooted: yes

**Comment by xLexip** [comment]
Which VPN?

**Comment by otohime-inari** [comment]
own PPTP on Mikrotik at home
own L2TP on Mikrotik at work
stock oos on this phone connect normally 

In mikrotik logs only
pptp, info TCP connection established from 333.33.333.33

OpenVPN works fine

**Comment by xLexip** [comment]
This issue relates to a specific vpn. I will close this isse because it is not applicable to VPNs in general. Nevertheless I will put it on the list.
