### ISSUE TITLE
VoWIFI does not work at the moment 

### ISSUE THREAD

**Issue by xLexip** [xLexip/pe#7]

**Comment by HBP87** [comment]
Is volte still broken?

**Comment by xLexip** [comment]
> Is volte still broken?

It's still not working the way it should.

**Comment by StimuL992** [comment]
I'm waiting for a decision

**Comment by Addy2297** [comment]
Awaiting a response on this. Looking forward to flashing this ROM on my daily driver.

**Comment by xLexip** [comment]
> I'm waiting for a decision


> Awaiting a response on this. Looking forward to flashing this ROM on my daily driver.


Personally, I don't use volte stuff. So I need someone to test it and tell me what's wrong. ¯\_(ツ)_/¯

**Comment by xLexip** [comment]
Fixed with 2021-03-13
