### ISSUE TITLE
Assistant: Voice Match Issues

### ISSUE THREAD

**Issue by xLexip** [xLexip/pe#9]
**Bug Description:**
Voice Match cannot be permanently activated.

**Comment by xLexip** [comment]
Impossible to fix atm.

**Comment by Pranav435** [comment]
Hi I am facing the same issue. Is there any guarantee it will be fixed in the March update?

**Comment by xLexip** [comment]
> Hi I am facing the same issue. Is there any guarantee it will be fixed in the March update?

No guarantee. Unfortunately, I cannot see into the future.

**Comment by Pranav435** [comment]
Hi

Lol, well I should've phrased that in a more diplomatic way.
Am I allowed to look at the sourcecode of the project? I may find something via looking into it.

**Comment by xLexip** [comment]
> Lol, well I should've phrased that in a more diplomatic way.
> Am I allowed to look at the sourcecode of the project? I may find something via looking into it.

Feel free to do that, it's visible to everyone.

**Comment by Resurrection2981** [comment]
> Impossible to fix atm.

@Maitreya29 (https://t.me/orangefoxop5t) found a fix
![image](https://user-images.githubusercontent.com/45873933/108615217-c8c2c700-743c-11eb-8b02-a3f71ad25a5d.png)
But he drop PEX, and then release new ROM, now this issue fix on ROM nezuko (https://forum.xda-developers.com/t/official-11-nezukoos.4231395/)
![image](https://user-images.githubusercontent.com/45873933/108615260-4f77a400-743d-11eb-8eaa-3d9f4846b3b5.png)
Hope fix on PE.

**Comment by xLexip** [comment]
> @Maitreya29 (https://t.me/orangefoxop5t) found a fix

Nope, he hasn't. ¯\_(ツ)_/¯

**Comment by Maitreya29** [comment]
> > Impossible to fix atm.
> 
> @Maitreya29 (https://t.me/orangefoxop5t) found a fix
> ![image](https://user-images.githubusercontent.com/45873933/108615217-c8c2c700-743c-11eb-8b02-a3f71ad25a5d.png)
> But he drop PEX, and then release new ROM, now this issue fix on ROM nezuko (https://forum.xda-developers.com/t/official-11-nezukoos.4231395/)
> ![image](https://user-images.githubusercontent.com/45873933/108615260-4f77a400-743d-11eb-8eaa-3d9f4846b3b5.png)
> Hope fix on PE.

Ah well the fix was broken with last security patch merge, Won't work.

**Comment by Maitreya29** [comment]
@xLexip the issue is source side and not something from your trees. It's happening on other devices as well. I recommend closing this issue.

**Comment by xLexip** [comment]
> @xLexip the issue is source side and not something from your trees. It's happening on other devices as well. I recommend closing this issue.

Yeah, I know. But i wanna inform the users anyways as it's important to some.

**Comment by Resurrection2981** [comment]
> > @xLexip the issue is source side and not something from your trees. It's happening on other devices as well. I recommend closing this issue.
> 
> Yeah, I know. But i wanna inform the users anyways as it's important to some.

Yes, I feel bad without this feature, It turns out that this problem also occurs on other devices? I even want to replace my OP5 because this reason.

**Comment by Resurrection2981** [comment]
> > > @xLexip the issue is source side and not something from your trees. It's happening on other devices as well. I recommend closing this issue.
> > 
> > 
> > Yeah, I know. But i wanna inform the users anyways as it's important to some.
> 
> Yes, I feel bad without this feature, It turns out that this problem also occurs on other devices? I even want to replace my OP5 because this reason.

Not only can't enable voice match, all of google apps can't hear me.
This happen before. When I was on PE Q, google apps can hear me, but it doesn't work after an new update. I compare the difference between the two builds, I find the different finally and help Joey Yu to fixed, but it broke again on R.

**Comment by xLexip** [comment]
Fixed with 0409
Shout out to @Maitreya29 for reviving it for the 1+ 5 series.
